config/routes.rb
Rails.application.routes.draw do
  get 'feedback_messages/new'

  get 'feedback_messages/create'

  root 'site#index'

  devise_for :users, :controllers => {
      :confirmations => "users/confirmations",
      :omniauth_callbacks => "users/omniauth_callbacks",
      :passwords => "users/passwords",
      :registrations => "users/registrations",
      :sessions => "users/sessions",
      :unlocks => "users/unlocks"
  }
  devise_for :admins, :controllers => {
      :sessions => "admins/sessions"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  post "check", :to => "orders#check"
  post "pay", :to => "orders#pay"
  get "pay", :to => "orders#pay"
  get "success", :to => "orders#success"
  get "fail", :to => "orders#fail"

  get "search", :to => "products#search"
  post "search", :to => "products#search_live"
  get "shop", :to => "products#index"
  get "shop/product/:id", :to => "products#show", :by => "shop", :as => "product"
  get "shop/:type_id/product/:id", :to => "products#show", :by => "shop", :as => "product_type"

  resources :order_records, :only => [:destroy, :update]
  resources :orders, :only => [:index, :edit, :show, :update], :path => :cart
  resources :products, :only => [:create], :path => :cart

  get "subjects", :to => "subject_tags#index"
  get "subject/:id", :to => "subject_tags#show", :as => "subject"
  get "subject/:subject_id/product/:id", :to => "products#show", :by => "subject", :as => "product_subject"
  get "subject/:subject_id/:id", :to => "type_tags#show", :by => "subject", :as => "subject_type"
  get "subject/:subject_id/:type_id/product/:id", :to => "products#show", :by => "subject", :as => "product_subject_type"

  get "regions", :to => "region_tags#index"
  get "region/:id", :to => "region_tags#show", :as => "region"
  get "region/:id/video", :to => "region_tags#video", :as => "region_video"
  get "region/:region_id/product/:id", :to => "products#show", :by => "region", :as => "product_region"
  get "region/:region_id/:id", :to => "type_tags#show", :by => "region", :as => "region_type"
  get "region/:region_id/:type_id/product/:id", :to => "products#show", :by => "region", :as => "product_region_type"

  get "categories", :to => "category_tags#index"
  get "category/:id", :to => "category_tags#show", :as => "category"
  get "category/:category_id/product/:id", :to => "products#show", :by => "category", :as => "product_category"
  get "category/:category_id/:id", :to => "type_tags#show", :by => "category", :as => "category_type"
  get "category/:category_id/:type_id/product/:id", :to => "products#show", :by => "category", :as => "product_category_type"

  get "mass_media", :to => "site#mass_media"
  get "news", :to => "site#news"
  get "may_9th", :to => "site#may_9th"
  get "about", :to => "site#about"
  get "competition", :to => "site#competition"
  get "exclusive", :to => "site#exclusive"
  get "exclusive_gallery", :to => "site#exclusive_gallery"
  get "exclusive_popup", :to => "site#exclusive_popup"
  get "oferta_popup", :to => "site#oferta_popup"
  get "video_popup", :to => "site#video_popup"
  get "product_popup", :to => "site#product_popup"
  get "me", :to => "site#account"

  resources :feedback_messages, :only => [:new, :create], :path => :contacts

  resources :addresses, :only => [:index, :create, :update, :destroy]
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :authenticate_user!, :only => :account

  def index
    @articles = Article.order(:created_at => :asc).reverse_order.limit(2).reverse
    @banners = Banner.all
  end

  def mass_media
    @articles = Article.all.page params[:page]
  end

  def may_9th
  end

  def news
    @news = News.all.page params[:page]
  end

  def about
  end

  def competition
  end

  def exclusive
  end

  def faq
  end

  def exclusive_gallery
  end

  def account
  end

  def oferta_popup
    render :partial => "oferta_popup"
  end

  def exclusive_popup
    render :partial => "exclusive_popup"
  end

  def video_popup
    render :partial => "video_popup"
  end

  def product_popup
    render :partial => "product_popup"
  end
end

app/views/site/_exclusive_popup.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header"> <i class="close fa fa-times btooltip" data-toggle="tooltip" data-placement="top" title="" data-dismiss="modal" data-original-title="Закрыть"></i>
      <h2>Помощь в заполнении формы</h2>
      <h3>Требования к вашему фото</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente asperiores modi nihil velit accusantium, perspiciatis numquam maiores quos voluptatibus, nulla voluptatum vel similique ex reiciendis aliquid sunt tempora veniam quasi? Reprehenderit incidunt eveniet maiores veritatis ipsa, quia culpa dolor. Earum dicta maiores facere optio pariatur assumenda ipsam fuga dolorum ipsum ullam laboriosam voluptatibus inventore, repellat?
      </p>
      <h3>Информация по шрифтам</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente asperiores modi nihil velit accusantium, perspiciatis numquam maiores quos voluptatibus, nulla voluptatum vel similique ex reiciendis aliquid sunt tempora veniam quasi? Reprehenderit incidunt eveniet maiores veritatis ipsa, quia culpa dolor. Earum dicta maiores facere optio pariatur assumenda ipsam fuga dolorum ipsum ullam laboriosam voluptatibus inventore, repellat? Quisquam enim minima ullam! Ipsam, quod quas iste at ratione suscipit! Tempore laborum fugiat repellat natus voluptatum facilis quae voluptate pariatur a? Quis laborum fugit enim debitis incidunt nobis quia aperiam qui, autem velit, corrupti! Consequuntur perspiciatis placeat nemo dicta ab, quidem ad eligendi accusamus non explicabo adipisci reprehenderit commodi, ut id, eaque provident esse quia eius dolor illo delectus necessitatibus deserunt. Illo eius sed odio, maiores et ab unde, asperiores modi quas aperiam voluptates incidunt, quod ipsam aliquam rem? Doloremque enim dicta veritatis eum dolorem accusamus, rerum ipsam iste repellat, commodi quas blanditiis ducimus dolor voluptatum deserunt ex sit, labore perferendis! Repellat corporis laudantium, aut beatae quae laboriosam itaque ipsa consequatur assumenda voluptate facilis quod labore, omnis harum nemo tempora iure fugit esse? Odit dolorem, repudiandae consectetur magnam dolor delectus, voluptate expedita voluptas ipsa provident ad aliquam atque explicabo quo cumque, nostrum consequuntur quia numquam consequatur?
      </p>
    </div>
  </div>
</div>

app/views/site/_product_popup.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <i class="close fa fa-times btooltip" data-toggle="tooltip" data-placement="top" title="" data-dismiss="modal" data-original-title="Закрыть"></i>
      <h2>Надпись</h2>
      <<iframe class="frrr" src=http://www.youtube.com/embed/AYI6y4WNCZE?rel=0&autoplay=0
              frameborder="0" allowfullscreen></iframe>>
    </div>
  </div>
</div>

app/views/site/_video_popup.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <i class="close fa fa-times btooltip" data-toggle="tooltip" data-placement="top" title="" data-dismiss="modal" data-original-title="Закрыть"></i>
      <h2>Проект РосПатриот</h2>
      <iframe class="frrr" src=http://www.youtube.com/embed/AYI6y4WNCZE?rel=0&autoplay=1
              frameborder="0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/site/about.html.erb
<div id="content-wrapper-parent">
  <div id="content-wrapper">
    <div id="content" class="container clearfix">
      <div id="breadcrumb" class="row breadcrumb">
        <div class="" itemprop="breadcrumb">
          <%= link_to "Главная", root_path, :class => "homepage-link", :title => "Вернуться на главную" %>
          <i class="fa fa-angle-right"></i>
          <span class="page-title">О нас</span>
        </div>
      </div>
      <section class="row content">
        <div id="col-main" class="blog blog-page col-content col-sm-15 col-md-15">
          <h1 id="page-title" class="large">О нас</h1>

          <div class="not-animated" data-animate="fadeInLeft" data-delay="300">
            <p><span class="red size">Р</span>осПатриот – это новый современный проект в сфере индустрии моды и одежды. Идея проекта направлена на объединение всей России по средствам создания уникальных дизайнерских образов.</p>

            <p><span class="red size">Д</span>анный проект предлагает объединение, консолидацию российского общества вокруг базисных вещей: культуры, истории и прогресса России. Мы хотим, чтобы каждый гражданин почувствовал себя частью Великой страны. Наша одежда позволит это сделать абсолютно каждому! А именно почувствовать причастность к своему государству, к той малой Родине, с которой  человека объединяет долголетняя связь и привязанность. К тому месту, где он родился, провел свои школьные, студенческие годы и другие приятные моменты своей жизни.</p>










            <p><span class="red size">Г</span>де бы человек не находился, в любой точке земного шара, он может заказать через наш он-лайн магазин частицу своей Родины – частицу России!</p>
          </div>
          <!--<img src="<%= image_path "about-photo.jpg" %>" class="img-responsive not-animated"
               data-animate="fadeIn" data-delay="300" height="283" width="866" alt="">-->
          <div class="not-animated sry-se" data-animate="fadeInLeft" data-delay="300">
            <h3><i class="swing fa fa-dot-circle-o red"></i> ЦЕЛЬ ПРОЕКТА</h3>


            <p class="boldy">Целью компании РосПатриот является создание как исторического, так и современного образа России на одежде и аксессуарах. Мы производим креативную, качественную и комфортную одежду на каждый день с неповторимым дизайном и пошивом. </p>

            <p class="boldy"> Созданный нами интернет-магазин несёт в себе не только общепринятый функционал магазинов такого рода, но а также рассказывает о России, её городах. Любой человек на нашем сайте может заказать для себя понравившееся изделие о России, с одним из специально разработанных дизайнерами рисунков, оплатить его удобным способом и получить в любой точке мира.</p>

            <img src="<%= image_path "rls.jpg" %>" class="img-responsive not-animated"
                 data-animate="fadeIn" data-delay="300" height="283" width="866" alt="">


            <p class="boldy" style="margin-top: 20px;"> У нас на сайте представлены майки с надписями и на английском языке. Так что каждый желающий сможет дарить нашу продукцию своим знакомым из других стран, тем самым показывая им интересную, незнакомую до этого Россию в изображениях: с ее неповторимыми пейзажами, памятниками, историческими личностями и всеми самыми известными достопримечательностями нашей необъятной страны!</p>

            <p class="boldy">РосПатриот – это самый лучший и простой способ приобрести себе запоминающуюся частичку России, родного края! У нас Вы найдете все: от Калининграда до Владивостока! </p>

            <p class="boldy">
              Желаем Вам приятных и успешных покупок!<br>

              Команда РосПатриот.
            </p>
          </div>

<!--
          <div class="not-animated st-res" data-animate="fadeInLeft" data-delay="300">
            <h3><i class="swing fa fa-question-circle-o red"></i>  Как сделать заказ на сайте:</h3>

            <p class="boldy">• Выберите интересующий товар, а так - же нужный размер </p>
            <p class="boldy">• Все товары, которые представленны на нашем сайте, есть в наличии </p>
            <p class="boldy">• Размеры, временно отсутствующие на складе - на сайте не представленны </p>
            <p class="boldy">• Положите товар в корзину. Это действие выполняет кнопка "Купить" </p>
            <p class="boldy">• В корзине можно продолжить покупки, нажав кнопку"Продолжить покупки" или продолжить </p>
            <p class="boldy">• Оформление заказа кнопкой " Оформить заказ" </p>
            <p class="boldy">• Заполните "Информация для оплаты и доставки заказа" </p>
            <p class="boldy">• Выберите "Способ доставки" </p>
            <p class="boldy">• Ожидайте звонка менеджера в рабочие часы интернет-магазина. </p>
          </div>
-->
        </div>
        <div class="col-sm-5 col-md-5 sidebar">
          <div class="group_sidebar not-animated" data-animate="flip" data-delay="300">
            <div class="sb-wrapper">
              <div class="sb-title">Быть патриотом - это модно!</div>
              <img src="<%= image_path "ros-gerb-o-nas.jpg" %>" alt="" class="img-responsive">
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/site/account.html.erb
<div id="content-wrapper-parent">
  <div id="content-wrapper">
    <div id="content" class="container clearfix">
      <div id="breadcrumb" class="row breadcrumb">
        <div class="" itemprop="breadcrumb">
          <%= link_to "Главная", root_path, :class => "homepage-link", :title => "Вернуться на главную" %>
          <i class="fa fa-angle-right"></i>
          <span class="page-title">Мой аккаунт</span>
        </div>
      </div>
      <section class="row content">
        <div id="col-main" class="account-page col-sm-15 col-md-15 clearfix">
          <h1 id="page-title" class="unmargin-top">Мой аккаунт</h1>
          <button class="btn" onclick="window.location='<%= edit_user_registration_url %>'">Сменить пароль</button>
          <div id="customer_orders">
            <h4>История заказов</h4>
            <div class="row wrap-table">
              <table class="table-hover">
                <thead>
                <tr>
                  <th class="order_number">Заказ</th>
                  <th class="date">Дата</th>
                  <th class="payment_status">Статус оплаты</th>
                  <th class="fulfillment_status">Состояние</th>
                  <th class="total">Итого</th>
                </tr>
                </thead>
                <tbody>
                <% current_user.orders.each_with_index do |order, index| %>
                    <tr class="<%= index % 2 > 0 ? "odd" : "even" %>">
                      <td><%= link_to order.id, order %></td>
                      <td><span class="note"><%= l order.created_at.to_date %></span></td>
                      <td><span class="status_authorized"><%= order.payment_status_label %></span></td>
                      <td><span class="status_unfulfilled"><%= order.status_label %></span></td>
                      <td><span class="total"><span class="money" data-currency-eur="€120.00" data-currency-usd="$164.68" data-currency="USD"><%= order.total_price %> руб.</span></span></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-sm-5 col-md-5 sidebar">
          <div class="group_sidebar mobi-marg">
            <div class="row sb-wrapper unpadding-top">
              <div class="sb-title">Детали аккаунта</div>
              <ul id="customer_detail" class="list-unstyled sb-content">
                <li>
                  <address class="clearfix">
                    <div class="info">
                      <i class="fa fa-user"></i>
                        <span class="address-group">
                          <span class="author"><%= current_user.full_name %></span>
                          <span class="email"><%= current_user.email %></span>
                        </span>
                    </div>
                    <% if current_user.address %>
                        <div class="address">
                      <i class="fa fa-home"></i>
                        <span class="address-group">
                          <span class="address1"><%= current_user.address.to_s %><span class="phone-number"><%= current_user.address.phone %></span> </span>
                        </span>
                    </div>
                    <% end %>
                  </address>
                </li>
                <li class="bt">
                  <button class="btn" id="view_address" onclick="window.location='<%= addresses_url %>'">Посмотреть адреса</button>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/site/index.html.erb
<div id="content-wrapper-parent">
  <div id="content-wrapper">
    <div class="home-slider-wrapper clearfix">
      <div class="camera_wrap" id="home-slider">
        <% @banners.each do |banner| %>
            <div data-src="<%= image_path banner.image %>"><%= raw banner.content %></div>
        <% end %>
      </div>
    </div>
    <div id="bottom">
      <div class="container">
        <div id="bottom_blocks" class="row">

          <div class="col-md-4">
            <div class="bottom-block bbl1 not-animated" data-animate="fadeInRight" data-delay="300">
              <div class="block-logo">
                <a href="<%= shop_url %>"><i class="swing sizys fa fa-shopping-cart red"></i></a>
              </div>
              <div class="block-content">
                <div class="block-heading fsr">Уникальный магазин</div>
                <p class="block-caption">
                  <a class="scrolr2" href="<%= regions_url %>">Региональная продукция</a> это дизайнерские изделия с принтами вашего любимого города, а <a class="scrolr2" href="<%= subjects_url %>">общая продукция</a> - одежда с уникальными изображениями и неповторимым дизайном.
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="bottom-block bbl2 not-animated" data-animate="fadeInLeft " data-delay="300">
              <div class="block-logo">
                <i class="swing sizys2 fa fa-shield red"></i>
              </div>
              <div class="block-content">
                <div class="block-heading">100% Гарантия</div>
                <p class="block-caption"> В нашем магазине представлены товары высокого качества. Если вдруг товар Вам не подошел, мы вернем деньги или заменим товар!</p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="bottom-block bbl3 not-animated" data-animate="fadeInRight" data-delay="300">
              <div class="block-logo">
                <i class="swing sizys2 fa fa-rub red"></i>
              </div>
              <div class="block-content">
                <div class="block-heading">Удобная схема взаиморасчета</div>
                <p class="block-caption">В нашем интернет-магазине представлены любые удобные для Вас сервисы
                  оплаты!</p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="bottom-block bbl4 not-animated" data-animate="fadeInLeft " data-delay="300">
              <div class="block-logo">
                <a><i class="swing sizys fa fa-magic red"></i></a>
              </div>
              <div class="block-content">
                <div class="block-heading">Надпись на заказ</div>
                <p class="block-caption">Нанести свою надпись на наше изделие очень просто, для этого
                  при оформлении заказа выберите соответсвующий пункт.
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-4 center-main">
            <div class="bottom-block bbl5 not-animated" data-animate="fadeInLeft " data-delay="300">
              <div class="block-logo">
                <a href="<%= new_feedback_message_url %>"><i class="swing sizys fa fa-globe red"></i></a>
              </div>
              <div class="block-content">
                <div class="block-heading">Доставка в любую точку планеты</div>
                <p class="block-caption"> Мы работаем с лучшими и проверенными службами <a class="scrolr2" href="<%= new_feedback_message_url %>">доставки</a> в России и в мире!
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="content" class="clearfix">
      <section class="content">
        <div id="col-main" class="clearfix">
          <div class="container">
            <!--home content-->
            <div class="col-md-15">
              <header class="control-group clearfix">
                <span class="title-3 red"><i class="fa fa-signal blue"></i> ХИТЫ ПРОДАЖ</span>
              </header>

              <% @nav[:types].each do |type| %>
                  <section class="rel-container clearfix">
                    <div id="scroll_link_type_<%= type.id %>" class="title-1">
                      <span class="content-title"><%= type.name %></span>
                      <span class="sub-title"></span>
                    </div>
                    <div id="prod-related-wrapper">
                      <div class="prod-related clearfix">
                        <% delay_dur = 0; type.products_active.shuffle.each do |product| %>
                            <div class="element not-animated" data-animate="bounceIn" data-delay="<%= delay_dur %>">
                              <%= render product, :url => product_type_url(:type_id => type.id, :id => product.id) %>
                            </div>
                        <% delay_dur += 200 end %>
                      </div>
                    </div>
                  </section>
              <% end %>
            </div>
            <div class="home_banners_wrapper col-md-5">
              <div class="group_homebanner hidden-xs">
                <div class="home_banners_inner not-animated" data-animate="fadeIn" data-delay="300">
                  <div class="home_banners_container">
                    <hr>
                    <h3 class="sb-title"><i class="fa fa-folder-open-o red"></i> Каталог</h3>
                    <h4 class="sb-title"> Общая продукция</h4>
                    <!--  <h5 class="sb-title"> Подарите праздник себе и своим близким!</h5> -->
                    <ul class="list-unstyled sb-content list-styled">
                      <% @nav[:subjects].each do |subject| %>
                          <li>
                            <a class="sizeq2" href="javascript:displ('var-subject-<%= subject.id %>')">
                              <%= subject.name %>
                              <i class="fa fa-angle-down"></i>
                            </a>
                            <div id="var-subject-<%= subject.id %>" style="display: none;">
                              <ul>
                                <% @nav[:types].each do |type| %>
                                    <li>
                                      <a tabindex="-1" href="<%= subject_type_url :subject_id => subject.id, :id => type.id %>">
                                        <%= type.name %>
                                      </a>
                                    </li>
                                <% end %>
                              </ul>
                            </div>
                          </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
                <div class="sb-wrapper not-animated" data-animate="fadeIn" data-delay="300">
                  <h4> Региональная продукция</h4>
                  <!-- <h5 class="sb-title"> ВЫБЕРИТЕ СВОЙ
                       ЛЮБИМЫЙ УГОЛОК
                       РОССИИ!</h5>
                   <img class="imeger2" src="<%= image_path "ros.png" %>" alt=" "> -->
                  <ul class="list-unstyled sb-content list-styled">
                    <% @nav[:regions].each do |region| %>
                        <li>
                          <a class="sizeq2" href="javascript:displ('var-region-<%= region.id %>')">
                            <%= region.name %>
                            <i class="fa fa-angle-down"></i>
                          </a>
                          <div id="var-region-<%= region.id %>" style="display: none;">
                            <ul>
                              <% @nav[:types].each do |type| %>
                                  <li>
                                    <a tabindex="-1" href="<%= region_type_url :region_id => region.id, :id => type.id %>">
                                      <%= type.name %>
                                    </a>
                                  </li>
                              <% end %>
                            </ul>
                          </div>
                        </li>
                    <% end %>
                  </ul>
                </div>
                <hr>
                <!--
                <div class="home_banners_inner not-animated" data-animate="flipInX" data-delay="300">
                  <div class="home_banners_container">
                    <h3 class="sb-title"><i class="fa fa-film red"></i> Видео</h3>

                    <div id="home_banners" class="clearfix">
                      <div class="banner quick_shop" data-href="<%= video_popup_url %>"
                           data-target="#quick-shop-modal" data-toggle="modal">
                        <a href="#">
                          <img src="<%= image_path "video-main.png" %>" alt="">
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
                <hr>
                -->
                <div class="sb-wrapper not-animated" data-animate="fadeIn" data-delay="300">
                  <h3 class="topper"><i class="fa fa-question-circle red"></i> ЧТО НОВОГО?</h3>
                  <ul class="list-unstyled sb-content textwidget list-styled">
                    <% @articles.each do |article| %>
                        <li><h6 class="new-h6"><%= article.title %></h6></li>
                    <% end %>
                  </ul>
                 <!-- <button class="btn2 select-option" type="button"
                          onclick="window.location='<%= mass_media_url %>'">Сми о нас <i
                  class="fa fa-hand-o-left sizz"></i></button> -->
                </div>
                <div class="home_banners_inner not-animated" data-animate="flipInX" data-delay="300">
                  <div class="home_banners_container">

                    <div id="home_banners" class="clearfix">

                      <a target="_blank" href="http://podaripobedy.ru">
                        <img src="<%= image_path "banim.png" %>" alt="">
                      </a>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
<div class="modal fade" id="quick-shop-modal"></div>
<script type="text/javascript">
  $(document).ready(function () {
    $('.scroll_link').click(function () {
      // скорость скролла
      var speed = 1000;
      // место скролла
      var href = $(this).attr('href'),
          top = $(href).offset().top;
      $('html, body').animate({scrollTop: top}, speed, function(){
        window.location.href = href;
      });
      return false;
    });
  });
  // Parse URL Queries Method
  (function ($) {
    $.getQuery = function (query) {
      query = query.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
      var expr = "[\\?&]" + query + "=([^&#]*)";
      var regex = new RegExp(expr);
      var results = regex.exec(window.location.href);
      if (results !== null) {
        return results[1];
        return decodeURIComponent(results[1].replace(/\+/g, " "));
      } else {
        return false;
      }
    };
  })(jQuery);

  $(function () {

    // Change URIs
    $('.pill-switch').click(function () {
      var current_url = window.location.href;
      window.location = "?theme=pill";
    });

    $('.tab-switch').click(function () {
      var current_url = window.location.href;
      window.location = "?theme=tab";
    });

    $('.image-switch').click(function () {
      var current_url = window.location.href;
      window.location = "?theme=image";
    });

    $('.link-switch').click(function () {
      window.location = "?theme=link";
    });

    // Set theme based on URI
    if ($.getQuery('theme') === 'pill') {
      $(function () {
        $.scrollUp({
          animation: 'fade',
          activeOverlay: '#00FFFF',
          scrollText: 'Наверх',
        });
      });
      $('.pill-switch').addClass('active');
      $('#scrollUpTheme').attr('href', 'css/themes/pill.css?1.1');
    }
    else if ($.getQuery('theme') === 'link') {
      $(function () {
        $.scrollUp({
          animation: 'fade',
          activeOverlay: '#00FFFF',
          scrollText: 'Наверх',
        });
      });
      $('#scrollUpTheme').attr('href', 'css/themes/link.css?1.1');
      $('.link-switch').addClass('active');
    }
    else if ($.getQuery('theme') === 'image') {
      $(function () {
        $.scrollUp({
          animation: 'fade',
          activeOverlay: '#00FFFF',
          scrollImg: {active: true, type: 'background', src: 'img/top.png'}
        });
      });
      $('#scrollUpTheme').attr('href', 'css/themes/image.css?1.1');
      $('.image-switch').addClass('active');
    }
    else {
      $(function () {
        $.scrollUp({
          animation: 'slide',
          activeOverlay: '#00FFFF',
          scrollText: 'Наверх',
        });
      });
      $('#scrollUpTheme').attr('href', 'css/themes/tab.css?1.1');
      $('.tab-switch').addClass('active');
    }

    // Toggle overlay

    $('#toggleActive').click(function () {
      $('#scrollUp-active').toggle();

      var text = $(this).text() == 'Скрыть границу' ? 'Показать границу' : 'Скрыть границу';
      $(this)
          .text(text)
          .toggleClass('active');
    });

  });

</script>