config/routes.rb
Rails.application.routes.draw do
  get 'feedback_messages/new'

  get 'feedback_messages/create'

  root 'site#index'

  devise_for :users, :controllers => {
      :confirmations => "users/confirmations",
      :omniauth_callbacks => "users/omniauth_callbacks",
      :passwords => "users/passwords",
      :registrations => "users/registrations",
      :sessions => "users/sessions",
      :unlocks => "users/unlocks"
  }
  devise_for :admins, :controllers => {
      :sessions => "admins/sessions"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  post "check", :to => "orders#check"
  post "pay", :to => "orders#pay"
  get "pay", :to => "orders#pay"
  get "success", :to => "orders#success"
  get "fail", :to => "orders#fail"

  get "search", :to => "products#search"
  post "search", :to => "products#search_live"
  get "shop", :to => "products#index"
  get "shop/product/:id", :to => "products#show", :by => "shop", :as => "product"
  get "shop/:type_id/product/:id", :to => "products#show", :by => "shop", :as => "product_type"

  resources :order_records, :only => [:destroy, :update]
  resources :orders, :only => [:index, :edit, :show, :update], :path => :cart
  resources :products, :only => [:create], :path => :cart

  get "subjects", :to => "subject_tags#index"
  get "subject/:id", :to => "subject_tags#show", :as => "subject"
  get "subject/:subject_id/product/:id", :to => "products#show", :by => "subject", :as => "product_subject"
  get "subject/:subject_id/:id", :to => "type_tags#show", :by => "subject", :as => "subject_type"
  get "subject/:subject_id/:type_id/product/:id", :to => "products#show", :by => "subject", :as => "product_subject_type"

  get "regions", :to => "region_tags#index"
  get "region/:id", :to => "region_tags#show", :as => "region"
  get "region/:id/video", :to => "region_tags#video", :as => "region_video"
  get "region/:region_id/product/:id", :to => "products#show", :by => "region", :as => "product_region"
  get "region/:region_id/:id", :to => "type_tags#show", :by => "region", :as => "region_type"
  get "region/:region_id/:type_id/product/:id", :to => "products#show", :by => "region", :as => "product_region_type"

  get "categories", :to => "category_tags#index"
  get "category/:id", :to => "category_tags#show", :as => "category"
  get "category/:category_id/product/:id", :to => "products#show", :by => "category", :as => "product_category"
  get "category/:category_id/:id", :to => "type_tags#show", :by => "category", :as => "category_type"
  get "category/:category_id/:type_id/product/:id", :to => "products#show", :by => "category", :as => "product_category_type"

  get "mass_media", :to => "site#mass_media"
  get "news", :to => "site#news"
  get "may_9th", :to => "site#may_9th"
  get "about", :to => "site#about"
  get "competition", :to => "site#competition"
  get "exclusive", :to => "site#exclusive"
  get "exclusive_gallery", :to => "site#exclusive_gallery"
  get "exclusive_popup", :to => "site#exclusive_popup"
  get "oferta_popup", :to => "site#oferta_popup"
  get "video_popup", :to => "site#video_popup"
  get "product_popup", :to => "site#product_popup"
  get "me", :to => "site#account"

  resources :feedback_messages, :only => [:new, :create], :path => :contacts

  resources :addresses, :only => [:index, :create, :update, :destroy]
end

app/models/region_tag.rb
class RegionTag < ActiveRecord::Base
  has_and_belongs_to_many :products, inverse_of: :region_tags

  mount_uploader :image, RegionImageUploader
  mount_uploader :plug, RegionPlugUploader

  def products_active
    self.products.where :is_active => true
  end
end

app/controllers/region_tags_controller.rb
class RegionTagsController < ApplicationController
  def index
  end

  def show
    @region = (RegionTag.find_by_id(params[:id]) or not_found)
  end

  def video
    @region = (RegionTag.find_by_id(params[:id]) or not_found)
    render :partial => "video"
  end
end

app/views/region_tags/_video.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <i class="close fa fa-times btooltip" data-toggle="tooltip" data-placement="top" title="" data-dismiss="modal" data-original-title="Закрыть"></i>
      <h2><%= @region.name %></h2>
      <iframe class="frrr" src="<%= @region.video %>" frameborder="0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/region_tags/index.html.erb
<div id="content-wrapper-parent">
  <div id="content-wrapper">
    <div id="content" class="container clearfix">
      <div id="breadcrumb" class="row breadcrumb">
        <div class="" itemprop="breadcrumb">
          <%= link_to "Главная", root_path, :class => "homepage-link", :title => "Вернуться на главную" %>
          <i class="fa fa-angle-right"></i>
          <a href="<%= shop_url %>" class="homepage-link">Магазин</a>
          <i class="fa fa-angle-right"></i>
          <span class="page-title">Региональные товары</span>
        </div>
      </div>
      <section class="row content botts">
        <div id="col-main" class="blog blog-page col-content col-sm-20 col-md-20">
          <h1 id="page-title" class="large">Магазин</h1>

          <h2><i class="fa fa-map-marker red"></i> Товары с региональными принтами</h2>

          <h3 class="blue"> Выберите регион:</h3>

          <div class="row">
            <% delay_dur = 100; @nav[:regions].each do |region| %>
                <div class="col-md-10">
                  <div class="opasity-hover">
                    <div class="collection-panner not-animated" data-animate="flipInX" data-delay="<%= delay_dur %>">
                      <a href="<%= region_url region %>">
                        <img src="<%= image_path region.image_url(:thumb) %>" height="303" width="865"
                             class="img-responsive" alt="">
                      </a>
                    </div>
                    <div class="parralax1">
                      <div class="inners">
                        <div class="inners3 not-animated" data-animate="bounceInLeft" data-delay="<%= delay_dur %>">
                          <i class="fa fa-chevron-right "></i>
                          <%= region.name %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="botty2"></div>
                </div>
            <% delay_dur += 200 end %>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/region_tags/show.html.erb
<div id="content-wrapper-parent">
  <div id="content-wrapper">
    <div id="content" class="container clearfix">
      <div id="breadcrumb" class="row breadcrumb">
        <div class="" itemprop="breadcrumb">
          <%= link_to "Главная", root_path, :class => "homepage-link", :title => "Вернуться на главную" %> <i class="fa fa-angle-right"></i>
          <a href="<%= shop_url %>" class="homepage-link">Магазин</a> <i class="fa fa-angle-right"></i>
          <a href="<%= regions_url %>" class="homepage-link">Региональные товары</a>
          <i class="fa fa-angle-right"></i>
          <span class="page-title"><%= @region.name %></span>
        </div>
      </div>
      <section class="row content">
        <!--#col-main-->
        <div id="col-main" class="collection collection-page col-content col-sm-15 col-md-15">

          <div id="page-header">
            <h1 id="page-title">Продукция: <%= @region.name %></h1>
          </div>

          <div class="collection-warper clearfix">
            <div class="collection-panner not-animated" data-animate="fadeIn" data-delay="900">
              <img src="<%= image_path @region.image %>" class="img-responsive" alt="">
            </div>
            <% delay_dur = 100; @nav[:types].each do |type| %>
                <div class="parralax1">
                  <a href="<%= region_type_url :id => type.id, :region_id => @region.id %>">
                    <div class="inners">
                      <div class="inners2 not-animated" data-animate="bounceInLeft" data-delay="<%= delay_dur %>">
                        <i class="fa fa-chevron-right "></i>
                        <%= type.name %>
                      </div>
                    </div>
                  </a>
                </div>
            <% delay_dur += 200 end %>
          </div>

          <section class="rel-container clearfix">
            <div class="title-1">
              <span class="content-title"><%= @region.name %>: популярные товары</span>
              <span class="sub-title"></span>
            </div>
            <div id="prod-related-wrapper">
              <div class="prod-related clearfix">
                <% delay_dur = 0; @region.products_active.shuffle.each do |product| %>
                    <div class="element not-animated" data-animate="bounceIn" data-delay="<%= delay_dur %>">
                      <%= render product, :url => product_region_url(:region_id => @region.id, :id => product.id) %>
                    </div>
                <% delay_dur += 200 end %>
              </div>
            </div>
          </section>
        </div>
        <!--end #col-main-->

        <!--sidebar-->
        <div id="prodcoll" class="col-sm-5 col-md-5 sidebar">
          <div class="group_sidebar">
            <% unless @region.video.blank? %>
              <div class="home_banners_inner not-animated" data-animate="flipInX" data-delay="300">
                <div class="home_banners_container">
                  <h3 class="sb-title tit-pr">
                    <i class="fa fa-film red"></i>
                    <%= @region.name %> на видео
                  </h3>

                  <div id="home_banners" class="clearfix">
                    <div class="banner quick_shop" data-href="<%= region_video_url @region %>"
                         data-target="#quick-shop-modal" data-toggle="modal">
                      <a href="#">
                        <img class="vid-prod" src="<%= image_path @region.plug %>" alt=""></a>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="sb-wrapper">
              <div class="sb-title">
                <i class="fa fa-map-marker red"></i>
                <%= @region.name %>
              </div>
              <ul class="list-unstyled sb-content textwidget list-styled">
                <li>
                  <%= raw @region.description %>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!--end sidebar--> </section>
    </div>
  </div>
</div>
<div class="modal fade" id="quick-shop-modal"></div>