config/routes.rb
Rails.application.routes.draw do
  get 'feedback_messages/new'

  get 'feedback_messages/create'

  root 'site#index'

  devise_for :users, :controllers => {
      :confirmations => "users/confirmations",
      :omniauth_callbacks => "users/omniauth_callbacks",
      :passwords => "users/passwords",
      :registrations => "users/registrations",
      :sessions => "users/sessions",
      :unlocks => "users/unlocks"
  }
  devise_for :admins, :controllers => {
      :sessions => "admins/sessions"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

  post "check", :to => "orders#check"
  post "pay", :to => "orders#pay"
  get "pay", :to => "orders#pay"
  get "success", :to => "orders#success"
  get "fail", :to => "orders#fail"

  get "search", :to => "products#search"
  post "search", :to => "products#search_live"
  get "shop", :to => "products#index"
  get "shop/product/:id", :to => "products#show", :by => "shop", :as => "product"
  get "shop/:type_id/product/:id", :to => "products#show", :by => "shop", :as => "product_type"

  resources :order_records, :only => [:destroy, :update]
  resources :orders, :only => [:index, :edit, :show, :update], :path => :cart
  resources :products, :only => [:create], :path => :cart

  get "subjects", :to => "subject_tags#index"
  get "subject/:id", :to => "subject_tags#show", :as => "subject"
  get "subject/:subject_id/product/:id", :to => "products#show", :by => "subject", :as => "product_subject"
  get "subject/:subject_id/:id", :to => "type_tags#show", :by => "subject", :as => "subject_type"
  get "subject/:subject_id/:type_id/product/:id", :to => "products#show", :by => "subject", :as => "product_subject_type"

  get "regions", :to => "region_tags#index"
  get "region/:id", :to => "region_tags#show", :as => "region"
  get "region/:id/video", :to => "region_tags#video", :as => "region_video"
  get "region/:region_id/product/:id", :to => "products#show", :by => "region", :as => "product_region"
  get "region/:region_id/:id", :to => "type_tags#show", :by => "region", :as => "region_type"
  get "region/:region_id/:type_id/product/:id", :to => "products#show", :by => "region", :as => "product_region_type"

  get "categories", :to => "category_tags#index"
  get "category/:id", :to => "category_tags#show", :as => "category"
  get "category/:category_id/product/:id", :to => "products#show", :by => "category", :as => "product_category"
  get "category/:category_id/:id", :to => "type_tags#show", :by => "category", :as => "category_type"
  get "category/:category_id/:type_id/product/:id", :to => "products#show", :by => "category", :as => "product_category_type"

  get "mass_media", :to => "site#mass_media"
  get "news", :to => "site#news"
  get "may_9th", :to => "site#may_9th"
  get "about", :to => "site#about"
  get "competition", :to => "site#competition"
  get "exclusive", :to => "site#exclusive"
  get "exclusive_gallery", :to => "site#exclusive_gallery"
  get "exclusive_popup", :to => "site#exclusive_popup"
  get "oferta_popup", :to => "site#oferta_popup"
  get "video_popup", :to => "site#video_popup"
  get "product_popup", :to => "site#product_popup"
  get "me", :to => "site#account"

  resources :feedback_messages, :only => [:new, :create], :path => :contacts

  resources :addresses, :only => [:index, :create, :update, :destroy]
end

app/views/layouts/_cart.html.erb
<div class="cart-link">
  <a href="<%= orders_url %>" class="dropdown-toggle dropdown-link">
    <!-- <i class="sub-dropdown1"></i> -->
    <!-- <i class="sub-dropdown"></i> -->
    <div class="num-items-in-cart">
      <span class="icon">
        <i class="fa fa-shopping-cart"></i>
        <span class="number"><%= @cart.total_quantity %> товар(-ов)</span>
      </span>
      <!-- <i class="fa fa-angle-down"></i> -->
    </div>
  </a>
  <div id="cart-info" class="dropdown-menu">
    <div class="cart-heading"><a href="<%= orders_url %>">Корзина</a></div>
    <div id="cart-content">
      <% if @cart && @cart.order_records.count > 0 %>
          <div class="items">
            <% @cart.order_records.each do |record| %>
                <div class="row">
                  <div class="col-md-8 cart-left">
                    <a class="cart-image" href="<%= product_url(record.product) %>">
                      <img class="img-responsive" src="<%= image_path record.product.front_image_url(:thumb) %>" alt="">
                    </a>
                  </div>
                  <div class="col-md-12 cart-right">
                    <div class="cart-title">
                      <a href="#"><%= record.product.name %> / Цвет: <%= record.color %> / <%= record.size %></a>
                    </div>
                    <div class="cart-price"><%= record.quantity %><span class="x"> x </span><span class="money"><%= record.price %> руб.</span></div>
                  </div>
                </div>
            <% end %>
          </div>
      <% end %>
      <div class="row last">
        <div class="col-md-10 cart-subtotal">ИТОГО:<span class="money"><%= @cart.total_price %> руб.</span></div>
        <div class="col-md-10 action">
          <a href="<%= orders_url %>"><button class="btn">Заказать</button></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<% if Rails.env.production? %>
<!-- BEGIN JIVOSITE CODE {literal} -->
<script type='text/javascript'>
  (function(){ var widget_id = 'MHHSLK9zew';var d=document;var w=window;function l(){
    var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/'+widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);}if(d.readyState=='complete'){l();}else{if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();</script>
<!-- {/literal} END JIVOSITE CODE -->
<% end %>

<footer id="footer">
  <div class="container">
    <div id="footer-content">
      <div class="row footer-content-middle">
        <div id="widget-linklist1" class="col-sm-5 xxs ssx ">
          <div class="widget-wrapper not-animated" data-animate="fadeInLeft" data-delay="300">
            <h3>
              КОНТАКТЫ
            </h3>
            <ul class="list-unstyled list-styled">
              <li>
                <p>
                  <span class="boldy">Телефоны:</span> 8 (495) 134-31-08 / 8 (800) 505-39-61<br>
                  <span class="boldy">Email:</span> info@rospatriot.ru<br>
                  <span class="boldy">Адрес:</span> ул. Намёткина, д. 1, подъезд 7 <br>
                  <span class="boldy">Время работы:</span> пн-пт c 10 00 до 20 00

                </p>
              </li>
              <li>
                <h3><i class="fa fa-hand-o-down "></i>
                  САМОВЫВОЗ
                </h3>

                Ул. Намёткина, д. 1, подъезд 7.<br>
                Перед тем как подъехать<br>
                позвоните по тел. <span class="boldy">8 (495) 134-31-08</span>
                <a class="footer-cl" href="<%= new_feedback_message_url %>#page-title"><i class="fa fa-caret-right"></i>
                  Подробнее</a>
              </li>

            </ul>
          </div>
        </div>
        <div id="widget-twitter" class="col-sm-5 xxs ssx">
          <div class="widget-wrapper not-animated" data-animate="fadeInUp" data-delay="300">
            <h3>
              Твиттер
            </h3>
            <a class="twitter-timeline" data-theme="dark" href="https://twitter.com/ros_patriot" data-widget-id="559809693997355008" data-chrome="noborders nofooter transparent noscrollbar noheader" data-tweet-limit="2" data-link-color="#e60404" data-related="benward,endform">Твиты
              @Ros_Patriot</a>
          </div>
          <script>!function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
            if (!d.getElementById(id)) {
              js = d.createElement(s);
              js.id = id;
              js.src = p + "://platform.twitter.com/widgets.js";
              fjs.parentNode.insertBefore(js, fjs);
            }
          }(document, "script", "twitter-wjs");</script>

          <script>
            var hideTwitterAttempts = 0;
            function hideTwitterBoxElements() {
              setTimeout(function () {
                if ($('[class*=twitter-timeline]').length) {
                  $('[class*=twitter-timeline]').each(function () {

                    $(this).css({'width': '100%'});
                    var ibody = $(this).contents().find('body');
                    if (ibody.find('.timeline .stream .h-feed li.tweet').length) {
                      ibody.find('.p-name').css({'font-size': '12px', 'color': '#ffffff'});
                      ibody.find('.e-entry-title').css({'font-size': '12px', 'color': '#ffffff'});
                    }
                    else {
                      $(this).hide();
                    }
                  });
                }
                hideTwitterAttempts++;
                if (hideTwitterAttempts < 3) {
                  hideTwitterBoxElements();
                }
              }, 1500);
            }

            // somewhere in your code after html page load
            hideTwitterBoxElements();
          </script>

        </div>
        <div id="widget-linklist2" class="col-sm-5 ffx xxs ssx">
          <div class="widget-wrapper not-animated" data-animate="fadeInUp" data-delay="300">
            <h3>
              Сотрудничество
            </h3>
            <ul class="list-unstyled list-styled">
              <li>
                <p>Мы всегда открыты
                  для интересных
                  предложений.
                  По вопросам
                  сотрудничества
                  звоните по телефону:
<span class="brr-fxt">
8 (495) 783-71-00</span>
                </p>
              </li>
              <div id="widget-social">
                <div class="widget-wrapper not-animated" data-animate="fadeInUp" data-delay="300">
                  <div id="img-ros"></div>
                  <h3>
                    МЫ В СОЦСЕТЯХ
                  </h3>
                  <ul class="list-inline">
                    <li>
                      <a target="_blank" href="http://vk.com/rospt" class="btooltip swing" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Вконтакте"><i class="fa fa-vk icoc"></i></a>
                    </li>
                    <li>
                      <a target="_blank" href="https://www.facebook.com/groups/741747129244478/" class="btooltip swing" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Фейсбук"><i class="fa fa-facebook icoc cor-fot-set2"></i></a>
                    </li>
                    <li>
                      <a target="_blank" href="https://twitter.com/Ros_Patriot" class="btooltip swing" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Твиттер"><i class="fa fa-twitter icoc"></i></a>
                    </li>
                    <li>
                      <a target="_blank" href="http://instagram.com/ros_patriot" class="btooltip swing" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Инстаграм"><i class="fa fa-instagram cor-fot-set icoc"></i></a>
                    </li>
                  </ul>
                </div>
              </div>
            </ul>
          </div>
        </div>
        <div id="footer-about-us" class="col-sm-5">
          <div class="widget-wrapper not-animated" data-animate="fadeInRight" data-delay="300">
            <h3>
              О НАС
            </h3>
            <p class="content-about-us">
              РосПатриот – новый проект, который направлен на объединение всей России и русского мира. Мы хотим, чтобы
              каждый гражданин почувствовал себя частью своей великой страны. Наша одежда позволит Вам это сделать.
              Здесь, Вы найдете ваш любимый город России и заберете его с собой!</p>
          </div>
          <div class="widget-wrapper not-animated" data-animate="fadeInRight" data-delay="300">
            <h3>
              ОПЛАТА
            </h3>
            <p class="content-about-us">
              Вы можете оплатить Ваш заказ любым
              удобным для Вас способом, включая оплату наличными и безналичную оплату</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<div id="footer2">
  <div class="container">
    <div id="footer-content2">
      <div class="row footer-content-bottom">
        <div id="widget-linklist4" class="col-sm-15">
          <div class="widget-wrapper">
            <ul class="list-unstyled">
              <li>
                <div class="whites">2014-2016 © Rospatriot.ru — модный интернет-магазин одежды
                  и аксессуаров.</div>



              </li>
            </ul>
          </div>
          <div class="copyright">Все права защищены. Доставка по всей России!</div>
        </div>
        <div id="widget-payment" class="col-sm-5">
          <ul id="payments" class="list-inline animated">
            <li class="tada"><a href="javascript:" class="icons visa"></a></li>
            <li class="tada"><a href="javascript:" class="icons mastercard"></a></li>

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  jQuery(function ($) {
    // Modernizr
    if (Modernizr.touch) {
      // show the close overlay button
      $(".close-overlay").removeClass("hidden");
      // handle the adding of hover class when clicked
      $(".img").click(function (e) {
        if (!$(this).hasClass("hover")) {
          $(this).addClass("hover");
        }
      });
      // handle the closing of the overlay
      $(".close-overlay").click(function (e) {
        e.preventDefault();
        e.stopPropagation();
        if ($(this).closest(".img").hasClass("hover")) {
          $(this).closest(".img").removeClass("hover");
        }
      });
    } else {
      // handle the mouseenter functionality
      $(".img").mouseenter(function () {
            $(this).addClass("hover");
          })
          // handle the mouseleave functionality
          .mouseleave(function () {
            $(this).removeClass("hover");
          });
    }
  });
</script>
<% errors = flash[:error] %>
<div class="error-color"<%= raw " style=\"display: none;\"" if (errors.try(:count) or 0) == 0 %>>
  При заполнении формы были допущены следующие ошибки:<br/>
  <%= raw errors.try :join, "<br />" %>
</div>
<script type="text/javascript">
  jQuery(function($){
    $('.error-color').fadeOut(10000);
  });
</script>

app/views/layouts/_head.html.erb
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"/>
  <link rel="canonical" href="/"/>

  <meta name="description" content=""/>

  <title>РосПатриот - новая национальная идея</title>
  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"/>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

  <link href="https://netdna.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css" rel="stylesheet"
        type="text/css" media="all">
  <!--[if IE 8 ]>
  <link href="/stylesheets/ie8.css" rel="stylesheet" type="text/css" media="all">
  <![endif]-->
  <style rel="stylesheet" type="text/css">
    #java_error {
      padding-top: 18px;
      padding-bottom: 20px;
      font-size: 24px;
      height: px;
      width: 750px;
      text-align: center;
      margin: 0 auto;
      background-color: yellow;
    }

    #java_error span {
      color: blue;
      text-decoration: underline;
    }
    .marg-bott {
      margin-bottom: 20px;
    }

    .siz-404 {
      font-size: 20px;
    }
    .opasity-hover:hover {
      opacity: 0.9;
      -webkit-transition: all 0.2s ease-out;
      -moz-transition: all 0.2s ease-out;
      -o-transition: all 0.2s ease-out;
      -ms-transition: all 0.2s ease-out;
      transition: all 0.2s ease-out;
    }

    .botty2 {
      margin-bottom: 20px;
    }
    .v-larg{
      font-size: 80px !important;
      text-align: center;
      font-weight: 100;
    }

    .fa-s{
      font-size: 55px;
      vertical-align: middle;
      margin: 11px;
    }
    .centr-w{
      text-align: center;
      font-size: 32px;
    }

    .cen-404{
      margin: 50px auto;
      text-align: center;
    }

    .siz-404{
      font-size: 20px;
    }

    .midd-404{
      top: 40%;
    }
  </style>
  <script type="text/javascript">var i = 1;
  function addtext(el) {
    a = el.parentNode;
    a.innerHTML = a.innerHTML + '<br />' + (i++) + '-й <input type="file" name="file[]" />';
  }
  </script>
</head>

app/views/layouts/_header.html.erb
<header id="top" class="fadeInDownBig clearfix">
  <div class="absy"><i class="fa fa-heart red"></i> РосПатриот - новая национальная идея
  </div>
  <!--Top-->
  <div class="top">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-10 header-left hidden-xs">
          <div class="currencies-switcher">
            <div class="currency-plain">
              <ul class="currencies list-inline unmargin">
                <a href="<%= new_feedback_message_url %>"><i class="fa fa-phone red size"></i></a>
                <li><span>8 (495) 134-31-08  <span class="hidden-xs hidden-sm hidden-md bespl">Для Москвы</span>  </span></li>

              </ul>
              <ul class="currencies list-inline unmargin">
                <a href="mailto:info@rospatriot.ru"><i class="fa fa-phone red size"></i></a>
                <li><span>8 (800) 505-39-61  <span class="hidden-xs hidden-sm hidden-md bespl">Бесплатно по всей России</span> </span></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-10 col-lg-10 header-right hidden-xs">
          <div class="customer-links">
            <ul id="accounts" class="list-inline">
              <% if user_signed_in? %>
                  <li class="account">
                    <i class="fa fa-share red"></i>
                    <%= link_to "Личный кабинет", me_path %>
                  </li>
                  <li class="account">
                    <i class="fa fa-share red"></i>
                    <%= link_to "Выйти", destroy_user_session_path, :method => :delete %>
                  </li>
              <% else %>
                  <li class="login">
                    <span id="loginButton" class="dropdown-toggle" data-toggle="dropdown">
                      <i class="fa fa-user red"></i> Войти
                      <i class="sub-dropdown1"></i>
                      <i class="sub-dropdown"></i>
                    </span>
                    <div id="loginBox" class="dropdown-menu text-left">
                      <%= render :partial => "users/sessions/new", :user => User.new %>
                    </div>
                  </li>
                  <li class="register">
                    <i class="fa fa-chevron-circle-right red"></i>
                    <a href="<%= new_user_registration_url %>" id="customer_register_link">Регистрация</a>
                  </li>
              <% end %>
            </ul>


            <ul id="toper" class="list-inline">
              <div class="podp">Подписывайтесь и</br>
                следите за нами!</div>
              <li class="soc-size-head"><a target="_blank" href="http://vk.com/rospt" class="btooltip swing" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Вконтакте"><i class="soc-size-header fa fa-vk red size soc1"></i></a></li>
              <li class="soc-size-head"><a target="_blank" href="https://www.facebook.com/groups/741747129244478/" class="btooltip swing ne-he" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Фейсбук"><i class="fa fa-facebook red size soc2  soc-size-header"></i></a></li>
              <li class="soc-size-head"><a target="_blank" href="https://twitter.com/Ros_Patriot" class="btooltip swing" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Твиттер"><i class="fa fa-twitter red size soc3 soc-size-header"></i></a></li>
              <li class="soc-size-head"><a target="_blank" href="http://instagram.com/ros_patriot" class="btooltip swing" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Инстаграм"><i class="fa fa-instagram red size soc4 soc-size-header"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--Top other-->
  <div class="container">
    <div class="row top-other">
      <div class="top-logo col-md-4 logo-margin">
        <%= link_to root_path, :id => "site-title", :title => "РосПатриот - новая национальная идея" do %>
            <img class="img-responsive" src="<%= image_path "logo.png" %>" alt="РосПатриот - новая национальная идея">
        <% end %>
      </div>
      <div class="top-navigation col-md-11">
        <nav class="navbar" role="navigation">
          <div class="clearfix">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Навигация</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="is-mobile visible-xs">
              <ul class="list-inline">
                <li class="is-mobile-menu">
                  <div class="btn-navbar" data-toggle="collapse" data-target=".navbar-collapse">
										<span class="icon-bar-group">
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
										</span>
                  </div>
                </li>
                <li class="is-mobile-wishlist">
                  <a href="<%= me_url %>">
                    <i class="fa fa-share blue"></i>
                  </a>
                </li>
                <li class="is-mobile-login">
                  <div class="btn-group">
                    <div class="dropdown-toggle" data-toggle="dropdown">
                      <i class="fa fa-user blue"></i>
                    </div>
                    <ul class="customer dropdown-menu mobi-ots">
                      <%= render :partial => "users/sessions/new", :user => User.new, :mobile => true %>
                      <li class="account last reg-mob">
                        <a class="reg-mob-a" href="<%= new_user_registration_url %>">
                          регистрация</a>
                      </li>
                    </ul>
                  </div>
                </li>
                <li class="is-mobile-cart">
                  <a href="<%= orders_url %>">
                    <i class="fa fa-shopping-cart blue"></i>

                  </a>
                </li>
              </ul>
            </div>

            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav hoverMenuWrapper">
                <li class="">
                  <%= link_to root_path do %>
                      <span>Главная</span>
                  <% end %>
                </li>
                <li class="dropdown">
                  <a href="<%= shop_url %>" class="dropdown-toggle dropdown-link" data-toggle="dropdown">
										<span>
											Магазин</span>
                    <i class="fa fa-angle-down"></i>
                    <i class="sub-dropdown1 visible-md visible-lg"></i>
                    <i class="sub-dropdown visible-md visible-lg"></i>
                  </a>
                  <ul class="dropdown-menu mobs">
                    <li class="region-menu">
                      Выберите категорию</li>
                    <li class="last">
                      <a class="big-li" tabindex="-1" href="<%= subjects_url %>" >
                        Общие товары</a>
                    </li>
                    <% @nav[:subjects].each do |subject| %>
                        <li class="nono-menu">
                          <i class="fa fa-caret-right blue"></i> <a tabindex="-1" href="<%= subject_url subject %>">
                            <%= subject.name %>

                          </a>
                        </li>
                    <% end %>
                    <hr>
                    <li class="mleft-menu">
                      <a class="big-li" tabindex="-1" href="<%= regions_url %>">
                        Региональные товары</a>
                    </li>
                    <% @nav[:regions].each do |region| %>
                        <li class="nono-menu">
                          <i class="fa fa-caret-right blue"></i>
                          <a tabindex="-1" href="<%= region_url region %>">
                            <%= region.name %>

                          </a>
                        </li>
                    <% end %>
                  </ul>
                </li>


                <li class="">
                  <a href="<%= about_url %>">
                    <span>О НАС</span>
                  </a>
                </li>
                <li class="">
                  <%= link_to mass_media_path do %>
                      <span>НОВОСТИ</span>
                  <% end %>
                </li>


                <li class="">
                  <a href="<%= new_feedback_message_url %>">
                    <span>КОНТАКТЫ</span>
                  </a>
                </li>


                <!--
                <li class="konkurs">
                  <div>
                    <a href="<%= competition_url %>">
                      <span>КОНКУРС</span>
                    </a>
                  </div>
                </li>
-->
              </ul>
            </div>
          </div>
        </nav>
      </div>
      <div class="top-search col-md-5">
        <div id="search-results" style="display: none;"></div>
        <div class="header-search">
          <form id="header-search" class="search-form" action="<%= search_url %>" method="get">
            <button type="submit" class="search-submit" title="Найди все, что хочется">
              <i class="fa fa-search col-hov"></i>
            </button>
            <input type="text" name="query" value="<%= @query %>" accesskey="4" autocomplete="off" placeholder="Поиск..." />
          </form>
        </div>
        <div class="umbrella hidden-xs">
          <div id="umbrella" class="list-inline unmargin">
            <%= render "layouts/cart" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8 ]>
<html lang="en" class="no-js ie8"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="ru" class="no-js"> <!--<![endif]-->
<%= render 'layouts/head' %>
<body class="template<%= "Index" if controller.controller_name == "site" && controller.action_name == "index" %>" itemscope itemtype="http://schema.org/WebPage">

<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->

</body>
</html>